---
jobs:
  - name: hello-job
    plan:
      - task: say-hello
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: busybox
          run:
            path: sh
            args:
              - -c
              - |
                echo "Hello from Concourse!"
                echo "Current time: $(date)"
                sleep 5
                echo "Job completed successfully!"

  - name: test-job
    plan:
      - task: run-tests
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: busybox
          run:
            path: sh
            args:
              - -c
              - |
                echo "Running tests..."
                echo "Test 1: PASS"
                echo "Test 2: PASS"
                echo "Test 3: PASS"
                echo "All tests passed!"
